In [3]:
import pandas as pd
url = "https://raw.githubusercontent.com/ElenaVillano/databases/refs/heads/main/db_falsas_alarmas.csv"
df = pd.read_csv(url)

Base de datos
Incidentes viales reportados por C5

5.1 Contexto y estructura de la base de datos.


*¿Qué fénomenos registra la base?


La base mide incidentes viales que incluyen información sobre la fecha y hora de creación, así como el cierre de los reportes, el tipo de incidente, la alcaldía, la ubicación geográfica, la clasificación y el código de cierre. 


*¿Quién la produjo y con qué propósito?


La produjo el Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano de la CDMX (C5) con el próposito de llevar un registro de los incidentes viales, así como su estatus (abierto, cerrado) en la Ciudad de México.

¿Cuántas filas y columnas tiene?

In [4]:
#Estructura del DataFrame
df.shape

(124261, 14)

La base de datos contiene 14 columnas y 1242261 datos (con fecha de 21 de octubre del 2026.)

Variables

In [5]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud'],
      dtype='str')

*¿Qué significa cada variable? 
|Variable|Descripción|
|---|---|
|Folio|ID de cada incidente generado|
|Fecha y hora de creación|Fecha y hora de creación del folio|
|Fecha de cierre|Fecha y hora de cierre del folio|
|Tipo de incidente C4|Tipo de incidente|
|Indicente C4|Tipo específico de incidente|
|Delegación inicio|Alcaldía de creación del incidente|
|Latitud|Coordenada geográfica norte-sur|
|Longitud|Coordenada geográfica este-oeste|
|Código de cierre|ID final del incidente|
|Clas_conf_alarma|Clasificación del incidente|
|Tipo de entrada|Medio por el que se recibió el reporte|
|Delegación cierre|Alcaldía donce cierra el ID del incidente| 
|Colonia catálogo|Colonia donde se reporta el incidente|
|Alcaldía catálogo|Alcaldía donde se reporta el incidente|

5.2 Entidades y eventos

In [21]:
df.head()

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud
0,C5/20220923/04016,2022-09-23 18:38:34,2022-09-23 22:22:27,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,A,EMERGENCIA,LLAMADA DEL 911,VENUSTIANO CARRANZA,Venustiano Carranza,20 De Noviembre,-99.108352,19.443920
1,C5/20220829/00630,2022-08-29 02:56:31,2022-08-29 06:04:53,Accidente,Motociclista,CUAUHTEMOC,A,URGENCIAS MEDICAS,LLAMADA DEL 911,CUAUHTEMOC,Cuauhtémoc,Obrera,-99.140843,19.416669
2,C5/20220724/01907,2022-07-24 04:29:09,2022-07-24 07:36:49,Accidente,Choque sin lesionados,IZTAPALAPA,A,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,San Andres Tetepilco,-99.130702,19.371340
3,C5/20240215/03071,2024-02-15 16:20:03,2024-02-15 20:52:19,Accidente,Choque sin lesionados,LA MAGDALENA CONTRERAS,A,EMERGENCIA,LLAMADA DEL 911,LA MAGDALENA CONTRERAS,La Magdalena Contreras,La Cruz,-99.233973,19.305985
4,C5/20221006/03493,2022-10-06 19:33:05,2022-10-06 22:37:08,Accidente,Choque sin lesionados,IZTAPALAPA,F,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,Santa Martha Acatitla Norte,-99.013140,19.374476

|Código|Significado|
|----|----|
|A|Afirmativo: la unidad llegó y confirmó la emergencia.|
|N|Negativo: la unidad llegó, pero nadie confirmó la emergencia o solicitó apoyo.|
|I|Informativo: solicitud de información.|
|F|Falso: el incidente fue considerado falso en el lugar.|
|D|Duplicado: se registró el mismo incidente más de una vez.|

¿Cuál es la unidad de observación de cada fila?

La base de datos muestra incidentes viales ocurridos en la Ciudad de México, esta arroja datos del tipo de incidente (accidente, lesionado, sismo, etc), también porque medio se anuncio del incidente (Llamada al 911, botón de auxilio, etc.), además de registrar la ubicación exacta, así como la fecha y hora de la creación del incidente, el cual se registra en un folio y, como este fue resuelto por medio del código de cierre.

¿Cuáles son las entidades relevantes y cómo se identifican?

*Entiendase por entidad: Unidades de medida sobre las cuales se desea hacer predicción con apoyo de la información de las demás variables que acompañan la base de datos. A continuación, se muestran las entidades relevantes de la base de datos trabajada.

|Entidades relevantes|Cómo se clasifican|
|----|----|
|folio|Identificador único del incidente.|
|alcaldia_catalogo|Muestra la alcaldía a la que pertenece el incidente.|
|tipo_entrada|Forma mediante la cual se reporta el incidente.|
|codigo_cierre|Código que indica el estado o resultado del incidente.|

Con las variables que contamos podemos predecir sobre las variables 'alcaldia catalogo' (cuál es es la probabilidad de que un incidente se precedente en cada alcaldía); 'tipo de entrada' (conocer la probabilidad mediante la cual es más frecuente que se reportare un incidente). Al mismo tiempo, las variables antes mencionadas como las variables faltantes (que no son consideradas como entidades relevantes), pueden pronosticar el código de cierre que se le da a cada evento. 
*Otro ejemplo, sería conocer el tiempo transcurrido entre la creación de un folio hasta su cierre y con esto conocer la tendencia más cómun para un código de cierre.

¿Qué eventos aparecen y qué representan respecto de esas entidades?
*Entiendase por evento a las acciones y sucesos que afectan o describen al evento.

|Eventos relevantes|Qué representan respecto de esas entidades|
|----|----|
|tipo_incidicente_4|Indica el tipo de incidente (accidente,lesionado, cadáver, detención ciudadana, mi calle, sismo, mi taxi)|
|incidente c_4|Choque sin lesionados, choque con lesionados, atropellado, motociclista, etc. |
|clas_con_f_alarmas|Urgencias médicas, emergencia, delito, falsa alarma, incidentes externos|

¿Un folio identifica necesariamente un evento real distinto? Reflexionen sobre los duplicados.

In [28]:
print("Total de filas:", len(df))
print("Folios únicos:", df["folio"].nunique())
print("Folios faltantes:", df["folio"].isna().sum())
print("Folios duplicados:", df["folio"].duplicated().sum())

Total de filas: 124261
Folios únicos: 124261
Folios faltantes: 0
Folios repetidos: 0

Con la información de la base de datos, se encontró que no hay folios duplicados. Por lo tanto, cada folio representa un evento distinto.

La estructura de cada folio representa la forma, tipo y fecha del incidente. Se escogieron las variables asociadas de mayor peso para conocer el tipo de incidente.

In [9]:
display(
    df["codigo_cierre"]
    .value_counts(dropna=False)
    .to_frame("cantidad")
)

               cantidad
codigo_cierre
D                 52963
A                 45189
F                 25219
I                   890

In [10]:

display(df[["fecha_hora_creacion", "fecha_hora_cierre"]].dtypes)

display(
    df[["fecha_hora_creacion", "fecha_hora_cierre"]].head(10)
)

fecha_hora_creacion    str
fecha_hora_cierre      str
dtype: object

   fecha_hora_creacion    fecha_hora_cierre
0  2022-09-23 18:38:34  2022-09-23 22:22:27
1  2022-08-29 02:56:31  2022-08-29 06:04:53
2  2022-07-24 04:29:09  2022-07-24 07:36:49
3  2024-02-15 16:20:03  2024-02-15 20:52:19
4  2022-10-06 19:33:05  2022-10-06 22:37:08
5  2023-10-28 20:34:48  2023-10-30 15:04:24
6  2023-12-23 09:08:24  2023-12-23 13:06:59
7  2022-10-05 08:29:19  2022-10-05 11:37:01
8  2022-03-14 19:00:44  2022-03-14 22:09:13
9  2022-03-28 10:39:45  2022-03-28 14:44:10

5.3 Tipos, calidad y limpieza
Identifiquen tipos de datos y valores faltantes.

Identifiquen tipos de datos y valores faltantes.

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 124261 entries, 0 to 124260
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   folio                124261 non-null  str
 1   fecha_hora_creacion  124261 non-null  str
 2   fecha_hora_cierre    124261 non-null  str
 3   tipo_incidente_c4    124261 non-null  str
 4   incidente_c4         124261 non-null  str
 5   alcaldia_inicio      124253 non-null  str
 6   codigo_cierre        124261 non-null  str
 7   clas_con_f_alarma    124261 non-null  str
 8   tipo_entrada         124261 non-null  str
 9   alcaldia_cierre      124253 non-null  str
 10  alcaldia_catalogo    124131 non-null  str
 11  colonia_catalogo     121543 non-null  str
 12  longitud             124261 non-null  float64
 13  latitud              124261 non-null  float64
dtypes: float64(2), str(12)
memory usage: 13.3 MB

Se identificaron 12 variables str y dos variables float64.

Valores faltantes

In [12]:
df.isna().sum()

folio                     0
fecha_hora_creacion       0
fecha_hora_cierre         0
tipo_incidente_c4         0
incidente_c4              0
alcaldia_inicio           8
codigo_cierre             0
clas_con_f_alarma         0
tipo_entrada              0
alcaldia_cierre           8
alcaldia_catalogo       130
colonia_catalogo       2718
longitud                  0
latitud                   0
dtype: int64

Existen únicamente dos variables que cuentan con datos faltantes, alcaldía catálogo y colonia catálogo con 130 y 2718 respectivamente.

Revisen si las variables están representadas correctamente, especialmente fechas y horas.

In [29]:
df.head()

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud
0,C5/20220923/04016,2022-09-23 18:38:34,2022-09-23 22:22:27,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,A,EMERGENCIA,LLAMADA DEL 911,VENUSTIANO CARRANZA,Venustiano Carranza,20 De Noviembre,-99.108352,19.443920
1,C5/20220829/00630,2022-08-29 02:56:31,2022-08-29 06:04:53,Accidente,Motociclista,CUAUHTEMOC,A,URGENCIAS MEDICAS,LLAMADA DEL 911,CUAUHTEMOC,Cuauhtémoc,Obrera,-99.140843,19.416669
2,C5/20220724/01907,2022-07-24 04:29:09,2022-07-24 07:36:49,Accidente,Choque sin lesionados,IZTAPALAPA,A,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,San Andres Tetepilco,-99.130702,19.371340
3,C5/20240215/03071,2024-02-15 16:20:03,2024-02-15 20:52:19,Accidente,Choque sin lesionados,LA MAGDALENA CONTRERAS,A,EMERGENCIA,LLAMADA DEL 911,LA MAGDALENA CONTRERAS,La Magdalena Contreras,La Cruz,-99.233973,19.305985
4,C5/20221006/03493,2022-10-06 19:33:05,2022-10-06 22:37:08,Accidente,Choque sin lesionados,IZTAPALAPA,F,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,Santa Martha Acatitla Norte,-99.013140,19.374476

Después de la revisión, se encontró que las variables fecha_hora_creacación y fecha_hora_cierra se encuentran bajo una clasificación incorrecta. Las demás variables se encuentran correctamente descritas.

Hagan las conversiones necesarias y expliquen cada decisión.

In [30]:
df['fecha_hora_creacion'] = pd.to_datetime(df['fecha_hora_creacion'] , errors='coerce')
df['fecha_hora_cierre'] = pd.to_datetime(df['fecha_hora_cierre'] , errors='coerce')

In [16]:
df.dtypes

folio                             str
fecha_hora_creacion    datetime64[us]
fecha_hora_cierre      datetime64[us]
tipo_incidente_c4                 str
incidente_c4                      str
alcaldia_inicio                   str
codigo_cierre                     str
clas_con_f_alarma                 str
tipo_entrada                      str
alcaldia_cierre                   str
alcaldia_catalogo                 str
colonia_catalogo                  str
longitud                      float64
latitud                       float64
dtype: object

Se decidió realizar la conversión en las variables 'fecha_hora_creacion' y 'fecha_hora_cierre' para convertirlas a un formato de datetime64[us] que sea reconocible por Python.

Identifiquen posibles duplicados, categorías inconsistentes o coordenadas fuera del rango esperado, cuando aplique.

In [35]:
df["fecha_hora_creacion"].value_counts()

fecha_hora_creacion
2023-10-21 14:45:51    2
2023-12-03 17:42:18    2
2022-04-10 17:30:28    2
2023-11-18 23:21:46    2
2023-12-02 16:58:12    2
                      ..
2022-12-05 11:12:02    1
2022-10-29 11:09:14    1
2023-10-10 14:29:48    1
2023-05-16 11:29:35    1
2022-11-14 19:38:46    1
Name: count, Length: 124106, dtype: int64

In [36]:
df["fecha_hora_cierre"].value_counts()

fecha_hora_cierre
2023-11-04 19:33:22    8
2023-10-30 15:02:48    8
2023-12-26 20:02:40    8
2023-12-20 20:16:03    7
2023-10-25 11:17:27    6
                      ..
2022-10-03 00:16:56    1
2022-12-05 14:21:57    1
2022-10-29 14:20:07    1
2023-10-10 17:34:21    1
2022-11-14 22:40:52    1
Name: count, Length: 107462, dtype: int64

In [37]:
df["incidente_c4"].value_counts()

incidente_c4
Choque sin lesionados               56845
Choque con lesionados               36245
Atropellado                         13042
Motociclista                        12374
Volcadura                            2216
Ciclista                             1560
Persona atrapada / desbarrancada      681
Vehículo atrapadovarado               543
Choque con prensados                  241
Accidente automovilístico             206
Incidente de tránsito                  96
Otros                                  68
Vehiculo desbarrancado                 64
Monopatín                              53
Ferroviario                            22
Persona atropellada                     5
Name: count, dtype: int64

df["longitud"].value_counts()
df["latitud"].value_counts()

In [19]:
df["tipo_entrada"].value_counts()

tipo_entrada
LLAMADA DEL 911     111287
BOTÓN DE AUXILIO      6998
RADIO                 5312
CÁMARA                 332
REDES                  191
APLICATIVOS            126
LLAMADA APP911          15
Name: count, dtype: int64

Después de la revisión de cada una de las variables, se encontraron duplicados en las variables 'fecha_hora_creacion', 'fecha_hora_cierre' e incidente_c4 (con personas atropelladas y atropellado. No se encontraron categorías inconsistes.

Para coordenadas fuera del rango esperado, se delimito Longitud 99°21'53.64" W  98°56'25.08" W y Latitud19°02'53.52" N  19°35'34.08" N con datos del Instituto Nacional de Estadística y Geografía (INEGI).

In [62]:
fuera_cdmx = df[
    ~df["longitud"].between(-99.21, -98.56)
    | ~df["latitud"].between(19.02, 19.35)
]
print("\nCoordenadas fuera del rango:")
print(fuera_rango[["folio", "longitud", "latitud"]])

Coordenadas fuera del rango:
                  folio   longitud    latitud
26129   C5/220401/01123 -99.021432  19.632201
40950   C5/220401/01134 -99.021432  19.632201
59997   C5/220401/01137 -99.021432  19.632201
108069  C5/220401/01124 -99.021432  19.632201

Se encontraron 4 valores fuera del rango de la Ciudad de México.

5.4 Data Profiling o perfilado por tipo de variable

Categóricas: categorías, frecuencias y valores faltantes.

In [66]:
df.dtypes

folio                             str
fecha_hora_creacion    datetime64[us]
fecha_hora_cierre      datetime64[us]
tipo_incidente_c4                 str
incidente_c4                      str
alcaldia_inicio                   str
codigo_cierre                     str
clas_con_f_alarma                 str
tipo_entrada                      str
alcaldia_cierre                   str
alcaldia_catalogo                 str
colonia_catalogo                  str
longitud                      float64
latitud                       float64
dtype: object

Variables categóricas

In [69]:
vars_categoricas = df.select_dtypes(include='object').columns.tolist()
tabla_categoricas = pd.DataFrame({"Categóricas": vars_categoricas})

display(tabla_categoricas)

C:\Users\puman\AppData\Local\Temp\ipykernel_5868\3931289351.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  vars_categoricas = df.select_dtypes(include='object').columns.tolist()

         Categóricas
0              folio
1  tipo_incidente_c4
2       incidente_c4
3    alcaldia_inicio
4      codigo_cierre
5  clas_con_f_alarma
6       tipo_entrada
7    alcaldia_cierre
8  alcaldia_catalogo
9   colonia_catalogo

Frecuencias

In [74]:
def tabla_categoricas(df, columnas):
    """Genera un resumen de variables categóricas."""

    resultados = []

    for columna in columnas:

        frecuencias = df[columna].value_counts()

        resultado = {
            "variable": columna,
            "n_categorias": df[columna].nunique(),
            "n_faltantes": df[columna].isnull().sum(),
            "moda": frecuencias.index[0],
            "top_2": frecuencias.index[1] if len(frecuencias) > 1 else "-",
            "top_3": frecuencias.index[2] if len(frecuencias) > 2 else "-"
        }

        resultados.append(resultado)

    return pd.DataFrame(resultados)

tabla_categoricas(df, vars_categoricas)

,variable,n_categorias,n_faltantes,moda,top_2,top_3
0,folio,124261,0,C5/20220923/04016,C5/20220829/00630,C5/20220724/01907
1,tipo_incidente_c4,7,0,Accidente,Lesionado,Cadáver
2,incidente_c4,16,0,Choque sin lesionados,Choque con lesionados,Atropellado
3,alcaldia_inicio,16,8,IZTAPALAPA,GUSTAVO A. MADERO,CUAUHTEMOC
4,codigo_cierre,4,0,D,A,F
5,clas_con_f_alarma,5,0,URGENCIAS MEDICAS,EMERGENCIA,DELITO
6,tipo_entrada,7,0,LLAMADA DEL 911,BOTÓN DE AUXILIO,RADIO
7,alcaldia_cierre,16,8,IZTAPALAPA,GUSTAVO A. MADERO,CUAUHTEMOC
8,alcaldia_catalogo,16,130,Iztapalapa,Gustavo A. Madero,Cuauhtémoc
9,colonia_catalogo,1373,2718,Centro,Agricola Oriental,Agricola Pantitlan

En el frame anterior se puede notar las variables categóricas, sus frecuencias, así como los valores faltanes. Es importante mencionar que la fila 0, folio, se debe ignorar ya que esta no arroja información relevante, caso contrario a las demás variables.

Numéricas

In [77]:
vars_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
tabla_numericas = pd.DataFrame({"Numéricas": vars_numericas})

display(tabla_numericas)

  Numéricas
0  longitud
1   latitud

In [78]:
df[vars_numericas].describe()

            longitud        latitud
count  124261.000000  124261.000000
mean      -99.134031      19.381444
std         0.061571       0.071538
min       -99.352914      19.094877
25%       -99.174500      19.332895
50%       -99.136941      19.383000
75%       -99.092380      19.434346
max       -98.947940      19.632201

Como las variables númericas únicamente reflejan valores de latitud y longuitud, su interpretación depende de un análisis espacial.

Valores faltantes

In [80]:
df.isna().sum()

folio                     0
fecha_hora_creacion       0
fecha_hora_cierre         0
tipo_incidente_c4         0
incidente_c4              0
alcaldia_inicio           8
codigo_cierre             0
clas_con_f_alarma         0
tipo_entrada              0
alcaldia_cierre           8
alcaldia_catalogo       130
colonia_catalogo       2718
longitud                  0
latitud                   0
dtype: int64

In [81]:
# Conteo de valores faltantes por columna
faltantes = df.isna().sum()

# También calculamos el porcentaje
pct_faltantes = (faltantes / len(df) * 100).round(2)

# Unimos en una tabla y filtramos solo las que sí tienen faltantes
tabla_faltantes = pd.DataFrame({
    'valores_faltantes': faltantes,
    'porcentaje_%': pct_faltantes
})


tabla_faltantes[tabla_faltantes['valores_faltantes'] > 0]

                   valores_faltantes  porcentaje_%
alcaldia_inicio                    8          0.01
alcaldia_cierre                    8          0.01
alcaldia_catalogo                130          0.10
colonia_catalogo                2718          2.19

Información de la base de datos.

La base mide incidentes viales que incluyen información sobre la fecha y hora de creación, así como el cierre de los reportes, el tipo de incidente, la alcaldía, la ubicación geográfica, la clasificación y el código de cierre. 

La base cuenta con datos desde 2014 y se actualiza mensualmente.

Los folios (registros) son individuales ya que cada uno describe información de un evento en específico. 

Las variables más importantes son tipo de incidente, código de cierre, tipo de entrada y clas_con_f_alarmas.

Interpretación de los resultados 


Folio: Creación de registro de un incidente


Grupo: Tipo de incidente C4


Subgrupo: Incidente_C4


Estado: Ciudad de México

Con información de la base de datos y su análisis, se obtuvo la siguiente información. 

Sabemos que 42.63% son folios que registraron el mismo incidente más de una vez, mientras tanto el 36.37% fueron casos positivos donde la unidad llego y confirmó la emergencia. No se cuentan con registros negativos, es decir, que la unidad llego, pero nadie confirmó la emergencia. 

Por otra parte, los incidentes más comunes fueron choques sin lesionados, seguidos con choques con lesionados y atropellados. 

La forma predilecta por la cual se comunicó el incidente fue mediante llamadas del 911 con casi un 90%, seguido del botón de auxilio con un 5.6%.

Las alcaldías con mayor cantidad de accidentes fueron Iztapalapa, Gustavo A. Madero y Cuauhtémoc. 

Por último, la clasifición por incidente con mayor impacto fueron urgencias médicas, seguido de emergencias y délitos.