In [6]:
import pandas as pd
url = "https://raw.githubusercontent.com/ElenaVillano/databases/refs/heads/main/db_falsas_alarmas.csv"
df = pd.read_csv(url)

Base de datos
Incidentes viales reportados por C5

5.1 Contexto y estructura de la base de datos
*¿Qué fénomenos registra la base?
Incidentes viales que incluyen información sobre la fecha y hora de creación y cierre de los reportes, el tipo de incidente, la alcaldía, la ubicación geográfica, la clasificación y el código de cierre. 

*¿Quién la produjo y con qué propósito?
*La produjo el Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano de la CDMX (C5) con el próposito de llevar un registro de los incidentes viales, así como su estatus (abierto, cerrado) para llevar un registro.

¿Cuántas filas y columnas tiene?

In [7]:
#Estructura del DataFrame
df.shape

(124261, 14)

Variables

In [8]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud'],
      dtype='str')

*¿Qué significa cada variable? 
|Variable|Descripción|
|---|---|
|Folio|ID de cada incidente generado|
|Fecha y hora de creación|Fecha y hora de creación del folio|
|Fecha de cierre|Fecha y hora de cierre del folio|
|Tipo de incidente C4|Tipo de incidente|
|Indicente C4|Tipo específico de incidente|
|Delegación inicio|Alcaldía de creación del incidente|
|Latitud|Coordenada geográfica norte-sur|
|Longitud|Coordenada geográfica este-oeste|
|Código de cierre|ID final del incidente|
|Clas_conf_alarma|Clasificación del incidente|
|Tipo de entrada|Medio por el que se recibió el reporte|
|Delegación cierre|Alcaldía donce cierra el ID del incidente| 
|Colonia catálogo|Colonia donde se reporta el incidente|
|Alcaldía catálogo|Alcaldía donde se reporta el incidente|

Entidades y eventos
*¿Cuál es la unidad de observación de cada fila?
*¿Cuáles son las entidades relevantes y cómo se identifican?
*¿Qué eventos aparecen y qué representan respecto de esas entidades?
¿Un folio identifica necesariamente un evento real distinto? Reflexionen sobre los duplicados.

Tipos, calidad y limpieza
Identifiquen tipos de datos y valores faltantes.

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 124261 entries, 0 to 124260
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   folio                124261 non-null  str
 1   fecha_hora_creacion  124261 non-null  str
 2   fecha_hora_cierre    124261 non-null  str
 3   tipo_incidente_c4    124261 non-null  str
 4   incidente_c4         124261 non-null  str
 5   alcaldia_inicio      124253 non-null  str
 6   codigo_cierre        124261 non-null  str
 7   clas_con_f_alarma    124261 non-null  str
 8   tipo_entrada         124261 non-null  str
 9   alcaldia_cierre      124253 non-null  str
 10  alcaldia_catalogo    124131 non-null  str
 11  colonia_catalogo     121543 non-null  str
 12  longitud             124261 non-null  float64
 13  latitud              124261 non-null  float64
dtypes: float64(2), str(12)
memory usage: 13.3 MB

In [14]:
df.isna().sum()

folio                     0
fecha_hora_creacion       0
fecha_hora_cierre         0
tipo_incidente_c4         0
incidente_c4              0
alcaldia_inicio           8
codigo_cierre             0
clas_con_f_alarma         0
tipo_entrada              0
alcaldia_cierre           8
alcaldia_catalogo       130
colonia_catalogo       2718
longitud                  0
latitud                   0
dtype: int64

Se identificaron doce variables se encuentran almacenadas como texto (str) y dos como números decimales (flot64). Además únicamente dos variables cuentan con datos faltantes, alcaldía catálogo y colonia catálogo con 130 y 2718 respectivamente.

Revisen si las variables están representadas correctamente, especialmente fechas y horas.

In [16]:
df.head(3)

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud
0,C5/20220923/04016,2022-09-23 18:38:34,2022-09-23 22:22:27,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,A,EMERGENCIA,LLAMADA DEL 911,VENUSTIANO CARRANZA,Venustiano Carranza,20 De Noviembre,-99.108352,19.443920
1,C5/20220829/00630,2022-08-29 02:56:31,2022-08-29 06:04:53,Accidente,Motociclista,CUAUHTEMOC,A,URGENCIAS MEDICAS,LLAMADA DEL 911,CUAUHTEMOC,Cuauhtémoc,Obrera,-99.140843,19.416669
2,C5/20220724/01907,2022-07-24 04:29:09,2022-07-24 07:36:49,Accidente,Choque sin lesionados,IZTAPALAPA,A,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,San Andres Tetepilco,-99.130702,19.371340

Después de la revisión, se encontró que las variables fecha_hora_creacación y fecha_hora_cierra se encuentran bajo una clasificación incorrecta.

In [22]:
df[["fecha_hora_creacion","fecha_hora_cierre"]].head()

   fecha_hora_creacion    fecha_hora_cierre
0  2022-09-23 18:38:34  2022-09-23 22:22:27
1  2022-08-29 02:56:31  2022-08-29 06:04:53
2  2022-07-24 04:29:09  2022-07-24 07:36:49
3  2024-02-15 16:20:03  2024-02-15 20:52:19
4  2022-10-06 19:33:05  2022-10-06 22:37:08

Hagan las conversiones necesarias y expliquen cada decisión.
Se decidió realizar la conversión en las variables 'fecha_hora_creacion' y 'fecha_hora_cierre' para convertirlas a un formato de datetime64[us] que sea reconocible por Python.

In [29]:
df['fecha_hora_creacion'] = pd.to_datetime(df['fecha_hora_creacion'] , errors='coerce')
df['fecha_hora_cierre'] = pd.to_datetime(df['fecha_hora_cierre'] , errors='coerce')

In [30]:
df.dtypes

folio                             str
fecha_hora_creacion    datetime64[us]
fecha_hora_cierre      datetime64[us]
tipo_incidente_c4                 str
incidente_c4                      str
alcaldia_inicio                   str
codigo_cierre                     str
clas_con_f_alarma                 str
tipo_entrada                      str
alcaldia_cierre                   str
alcaldia_catalogo                 str
colonia_catalogo                  str
longitud                      float64
latitud                       float64
dtype: object

In [31]:
# Filas completamente duplicadas
print("Filas duplicadas:", df.duplicated().sum())

# Folios repetidos después de su primera aparición
print("Folios repetidos:", df["folio"].duplicated().sum())

# Número de folios diferentes
print("Folios únicos:", df["folio"].nunique())

Filas duplicadas: 0
Folios repetidos: 0
Folios únicos: 124261